%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%函数名称：adjust
%注：用于调整频偏，在接收端使用
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%函数作用：用于调整频偏，在接收端使用
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
close all;
clear;%清除寄存器
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%用户可修改参数%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%ratio_delicate粗调和精调的倍数
%ratio_mid粗调和中调的倍数
%threshold辅角相减的门限值，超出这个值就认为是异常值
%flag异常值的标签
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%用户不可修改参数%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%无
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%说明%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%之所以有threshold这个量是因为辅角值的范围是[-pi,pi]，如果频偏f是正数，那么前一个辅角值theta_n接近pi（或-pi）
%假如后一个辅角值theta_(n+1)=theta_n+(n+1)*f>pi,那么theta_(n+1)应该是取模（以pi为模），那么这样直接计算
%theta_(n+1)-theta_n就会出错，因此可以剔除这些点
%用户可修改参数
%读取文件
[Filename,path]= uigetfile('*.mat','Select the MATLAB code file');
input_ori=load([path,Filename]);
input_ori=input_ori.signal;
input=reshape(input_ori,length(input_ori),1);
version='4.0';
data='2015年10月19日';
frequency_ratio_delicate=100;%粗调和精调的倍数
frequency_ratio_mid=10;%粗调和中调的倍数
phase_ratio_delicate=100;%粗调和精调的倍数
phase_ratio_mid=10;%粗调和中调的倍数
threshold=1.5*pi;
flag=500;
%用户不可修改参数
% frequency_n_c=0;%粗调的数目
% frequency_n_d=0;%精调的数目
% frequency_n_m=0;%中调的数目
% phase_n_c=0;%粗调的数目
% phase_n_d=0;%精调的数目
% phase_n_m=0;%中调的数目
%程序内容
angle_input=angle(input);%输入信号的辅角
mean_angle=mean(angle_input);%辅角的平均值
phase_offset=mean_angle;%辅角的平均值设置为相偏
diff_angle=diff((angle_input));
diff_angle_adjust=diff_angle.*(diff_angle>(-threshold)).*(diff_angle<(threshold))+flag*((diff_angle<(-threshold))+(diff_angle>(threshold)));
if sum(diff_angle_adjust<500)==0
    frequency_offset=0;
else
frequency_offset=sum(diff_angle_adjust.*(diff_angle_adjust<500))/sum(diff_angle_adjust<500);
fc=500000;
fs=fc;
signal=input.*cos(2*pi*fc*transpose(1:length(input))/fs);
%t=0:1/fc:1/fc*(length(signal)-1);
%r1=r.*exp(-2*1j*pi*f_offset1_new*t);
frequency_offset=fre_offset_esti_new(signal,fc,fs);
frequency_offset=2*pi*frequency_offset/fc;
end
if frequency_offset~=0 
    %选出频偏frequency_offset的非零最高位，然后粗调的值为最高位的1/10，中调为最高位的1/100，精调为最高位的1/1000
    frequency_string=num2str(abs(frequency_offset));%转为字符串
    frequency_vector=(frequency_string~='0').*(frequency_string~='.');%选取字符串中不等于0且不是小数点的那些位，都设置为1,0和小数点都是0
    frequency_nonzeros=find(frequency_vector~=0);%找出非0的那些位数
    frequency_coarse_adjust=10^(-((frequency_nonzeros(1)))+1);%设置粗调步进大小
    frequency_delicate_adjust=frequency_coarse_adjust/frequency_ratio_delicate;%设置精调步进大小
    frequency_mid_adjust=frequency_coarse_adjust/frequency_ratio_mid;%设置中调步进大小
end
if frequency_offset==0
    frequency_coarse_adjust=10^(-4);
    frequency_mid_adjust=10^(-5);
    frequency_delicate_adjust=10^(-6);
end
%选出相偏phase_offset的非零最高位，然后粗调的值为最高位的1/10，中调为最高位的1/100，精调为最高位的1/1000
if phase_offset~=0 
    phase_string=num2str(phase_offset);%转为字符串
    phase_vector=(phase_string~='0').*(phase_string~='.');%选取字符串中不等于0且不是小数点的那些位，都设置为1,0和小数点都是0
    phase_nonzeros=find(phase_vector~=0);%找出非0的那些位数
    phase_coarse_adjust=10^(-((phase_nonzeros(1)))+1);%设置粗调大小
    phase_delicate_adjust=phase_coarse_adjust/phase_ratio_delicate;%设置精调大小
    phase_mid_adjust=phase_coarse_adjust/phase_ratio_mid;%设置中调大小
end
if phase_offset==0
    phase_coarse_adjust=10^(-4);
    phase_mid_adjust=10^(-5);
    phase_delicate_adjust=10^(-6);
end
hf=figure('Position',[100 20 800 600],'Name',['频偏相偏估计器',' Version:',version,' Date:',data,' Programmer:','张克终'],'NumberTitle','off');
hb=axes('Position',[0.05 0.6 0.25 1/3],'Box','on','DataAspectRatioMode','manual',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图
ha=axes('Position',[0.3 0.6 0.25 1/3],'Box','on','DataAspectRatioMode','manual',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图
hc=axes('Position',[0.05 0.25 0.45 0.25],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图
hd=axes('Position',[0.55 0.25 0.45 0.25],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图
he=axes('Position',[0.6 0.8 0.2 0.15],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图original real
hg=axes('Position',[0.8 0.8 0.2 0.15],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图original imag
hh=axes('Position',[0.8 0.6 0.2 0.15],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图adjust real
hi=axes('Position',[0.6 0.6 0.2 0.15],'Box','on',...
    'XLimMode','manual','XLimMode','manual','XLim',[-1.5 1.5],'YLim',[-1.5 1.5]...
    );%画图，画出频偏纠正之后的图adjust imag
output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));
axes(hb);
scatter(real(input),imag(input),'.');grid on;axis equal;
title('接收信号');
axes(ha);
scatter(real(output),imag(output),'.');grid on;axis equal;
title(['频偏=',num2str(frequency_offset),'相偏=',num2str(phase_offset)]);
axes(hc);
stem(1:length(input),angle(input),'.');
title('原始信号的相位');
grid on;
axes(hd);
stem(1:length(output),angle(output),'.');
title('恢复后信号的相位');
grid on;
axes(he);
%subplot(1,2,1);
stem(1:length(input),real(input),'.');
title('恢复前信号，实部');
grid on;
axes(hg);
%subplot(1,2,1);
stem(1:length(input),imag(input),'.');
title('恢复前信号，虚部');
grid on;
axes(hh);
stem(1:length(output),real(output),'.');
title('恢复后信号，实部');
grid on;
axes(hi);
stem(1:length(output),imag(output),'.');
title('恢复后信号，虚部');
grid on;
command_plot=['axes(hh);',...
'stem(1:length(output),real(output),''.'');',...
'title(''恢复后信号，实部'');',...
'grid on;',...
'axes(hi);',...
'stem(1:length(output),imag(output),''.'');',...
'title(''恢复后信号，虚部'');',...
'grid on;'];
% subplot(1,2,2);
% stem(1:length(output),imag(output),'.');
% title('恢复后信号的相位，虚部');
% grid on;
%scatterplot(output);
%hfr1=uicontrol(gcf,'Style','frame','Position',[10 90 400 200]);

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_coarse_demo=uicontrol(hf,'Style','text','Position',[50,80,50,30],'String','频偏粗调');
 h_frequency_mid_demo=uicontrol(hf,'Style','text','Position',[120,80,50,30],'String','频偏中调');
 h_frequency_delicate_demo=uicontrol(hf,'Style','text','Position',[190,80,50,30],'String','频偏微调');
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_frequency_coarse_add=uicontrol(hf,'Style','pushbutton',...%频偏粗调+
    'Position',[50,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset+frequency_coarse_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);%调整之后的输出
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_mid_add=uicontrol(hf,'Style','pushbutton',...%频偏中调+
    'Position',[120,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset+frequency_mid_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...%调整之后的输出
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_delicate_add=uicontrol(hf,'Style','pushbutton',...%频偏微调+
    'Position',[190,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset+frequency_delicate_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...%调整之后的输出
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_coarse_substract=uicontrol(hf,'Style','pushbutton',...%频偏粗调
    'Position',[50,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset-frequency_coarse_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...%调整之后的输出
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_delicate_substract=uicontrol(hf,'Style','pushbutton',...%频偏中调
    'Position',[120,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset-frequency_mid_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...%调整之后的输出
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_frequency_mid_substract=uicontrol(hf,'Style','pushbutton',...%频偏微调
    'Position',[190,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset-frequency_delicate_adjust;'...%调整频偏值
        'phase_offset=phase_offset;'...%调整相偏值
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...%调整之后的输出
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_phase_coarse_demo=uicontrol(hf,'Style','text','Position',[260,80,50,30],'String','相偏粗调');
h_phase_mid_demo=uicontrol(hf,'Style','text','Position',[330,80,50,30],'String','相偏中调');
h_phase_delicate_demo=uicontrol(hf,'Style','text','Position',[400,80,50,30],'String','相偏微调');
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_phase_coarse_add=uicontrol(hf,'Style','pushbutton',...%相偏粗调+
    'Position',[260,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset+phase_coarse_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_phase_mid_add=uicontrol(hf,'Style','pushbutton',...%相偏中调+
    'Position',[330,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset+phase_mid_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_phase_delicate_add=uicontrol(hf,'Style','pushbutton',...%相偏微调
    'Position',[400,60,50,30],...
    'String','+',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset+phase_delicate_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_phase_coarse_substract=uicontrol(hf,'Style','pushbutton',...%相偏粗调
    'Position',[260,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset-phase_coarse_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_phase_delicate_substract=uicontrol(hf,'Style','pushbutton',...%相偏中调
    'Position',[330,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset-phase_mid_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 h_phase_mid_substract=uicontrol(hf,'Style','pushbutton',...%相偏微调
    'Position',[400,20,50,30],...
    'String','-',...
    'CallBack',...
        ['frequency_offset=frequency_offset;'...
        'phase_offset=phase_offset-phase_delicate_adjust;'...
        'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
        'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;',command_plot...
        ]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h_frequency_demo=uicontrol(hf,'Style','edit','Position',[500 40 80 40],'String',num2str(frequency_offset),...
    'CallBack',['frequency_str=get(h_frequency_demo,''String'');','frequency_offset=str2double(frequency_str);',...
    'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
    'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;']);
h_frequency_demo_text=uicontrol(hf,'Style','text','Position',[500 80 80 20],'String','频偏');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
h_phase_demo=uicontrol(hf,'Style','edit','Position',[600 40 80 40],'String',num2str(phase_offset),...
    'CallBack',['phase_str=get(h_phase_demo,''String'');','phase_offset=str2double(phase_str);',...
    'output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));'...
    'axes(ha);',...
        'scatter(real(output),imag(output),''.'');','grid on;','axis equal;','hold off;','title([''频偏='',num2str(frequency_offset),''相偏='',num2str(phase_offset)]);',...
        'axes(hd);','stem(1:length(output),angle(output),''.'');','title(''恢复后信号的相位'');','grid on;']);
h_phase_demo_text=uicontrol(hf,'Style','text','Position',[600 80 80 20],'String','相偏');
%end    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
explain=['本程序用于手动调整接收信号的频偏，通过观察信号的星座图、时域图以及相位图观察频偏和相偏大小，最后得到的频偏值','f','和相偏值p的用法：','第n个信号乘以e^{f*n+p}'];
h_explain_demo=uicontrol(hf,'Style','text','Position',[700 25 200 80],'String',explain);
%h_version_demo=uicontrol(hf,'Style','text','Position',[950 25 300 80],'String',['Version:',version,' Date:',data,' Programmer:','张克终']);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %调整频偏值
% frequency_offset=frequency_offset+frequency_n_d*frequency_delicate_adjust+frequency_n_c*frequency_coarse_adjust+frequency_n_m*frequency_mid_adjust;
% %调整相偏值
% phase_offset=phase_offset+phase_n_d*phase_delicate_adjust+phase_n_c*phase_coarse_adjust+phase_n_m*phase_mid_adjust;
% %调整之后的输出
% output=input*exp(-1i*phase_offset).*exp(-1i*frequency_offset*transpose(0:length(input)-1));
%EDN OF PROGRAMS
